# Generated by Django 4.2.23 on 2025-08-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='ACTIVE', help_text='Current status of the project', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Project due date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the project was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the project was last updated')),
                ('organization', models.ForeignKey(help_text='Organization that owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
