# Generated by Django 4.2.23 on 2025-08-26 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing and organization identification', unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email for the organization', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organization was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the organization was last updated')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
